import React, { useRef } from 'react';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { Download, FileText, TrendingUp, AlertCircle, Target, Zap, Layout, List } from 'lucide-react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

const ForensicReport = ({ businessData, analysisResult, lang = 'en' }) => {
    const reportRef = useRef();

    const t = {
        en: {
            btn: "Download Intelligence Report",
            title: "FORENSIC BUSINESS AUDIT",
            summary: "Executive Neural Summary",
            trends: "Performance Velocity",
            focus: "Strategic Focus Zones",
            recommendations: "Neural Directives",
            details: "Data Synoptics Matrix",
            generated: "Generated by FinAura Ultra v3.5",
            score: "COMPLIANCE SCORE",
            risk: "RISK LEVEL"
        },
        hi: {
            btn: "इंटेलिजेंस रिपोर्ट डाउनलोड करें",
            title: "फोरेंसिक बिजनेस ऑडिट",
            summary: "कार्यकारी सारांश",
            trends: "प्रदर्शन वेग",
            focus: "रणनीतिक फोकस क्षेत्र",
            recommendations: "रणनीतिक निर्देश",
            details: "डेटा सिनॉप्टिक्स मैट्रिक्स",
            generated: "FinAura Ultra v3.5 द्वारा उत्पन्न",
            score: "अनुपालन स्कोर",
            risk: "जोखिम स्तर"
        },
        ta: {
            btn: "நுண்ணறிவு அறிக்கையைப் பதிவிறக்குக",
            title: "வணிக தடயவியல் தணிக்கை",
            summary: "நிர்வாக சுருக்கம்",
            trends: "செயல்பாட்டு வேகம்",
            focus: "மூலோபாய மைய மண்டலங்கள்",
            recommendations: "மூலோபாய கட்டளைகள்",
            details: "தரவு மேட்ரிக்ஸ்",
            generated: "FinAura Ultra v3.5 மூலம் உருவாக்கப்பட்டது",
            score: "இணக்க மதிப்பெண்",
            risk: "ஆபத்து நிலை"
        }
    }[lang] || { en: {} };

    // Intelligent Chart Mapping with Variance Detection
    const getChartKeys = () => {
        if (!businessData || !businessData.length) return { x: 'index', y: 'value', y2: null };
        const keys = Object.keys(businessData[0]);

        // Find best X key (Time/Date based)
        const xKey = keys.find(k => /date|time|month|day|year|period|index|sl/i.test(k)) || keys[0];

        // Find all numerical keys
        const numKeys = keys.filter(k => {
            const val = businessData[0][k];
            return !isNaN(parseFloat(val)) && typeof val !== 'boolean';
        });

        // Sort by 'importance' based on common financial terms
        const sortedNumKeys = [...numKeys].sort((a, b) => {
            const weight = (key) => /revenue|sales|income|profit|amount|total|balance/i.test(key) ? 10 :
                /expense|cost|burn|tax|fee/i.test(key) ? 5 : 1;
            return weight(b) - weight(a);
        });

        const yKey = sortedNumKeys[0] || keys[1];
        const y2Key = sortedNumKeys[1] || null;

        return { x: xKey, y: yKey, y2: y2Key };
    };

    const { x: xKey, y: yKey, y2: y2Key } = getChartKeys();

    const downloadPDF = async () => {
        const element = reportRef.current;
        if (!element) return;

        // Ensure the element is "visible" for html2canvas
        const originalStyle = element.style.cssText;
        element.style.display = 'block';
        element.style.position = 'relative';
        element.style.left = '0';
        element.style.top = '0';

        // Neural Delay: Wait for SVG to fully paint
        await new Promise(resolve => setTimeout(resolve, 1000));

        try {
            const canvas = await html2canvas(element, {
                scale: 2,
                useCORS: true,
                backgroundColor: '#0a0a0c',
                logging: false,
                allowTaint: true,
                windowWidth: 1000
            });

            const imgData = canvas.toDataURL('image/png');
            const pdf = new jsPDF('p', 'mm', 'a4');
            const pdfWidth = pdf.internal.pageSize.getWidth();
            const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

            let heightLeft = pdfHeight;
            let position = 0;
            const pageHeight = pdf.internal.pageSize.getHeight();

            pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight, undefined, 'FAST');
            heightLeft -= pageHeight;

            while (heightLeft >= 0) {
                position = heightLeft - pdfHeight;
                pdf.addPage();
                pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight, undefined, 'FAST');
                heightLeft -= pageHeight;
            }

            pdf.save(`FinAura_Forensic_Report_${Date.now()}.pdf`);
        } catch (err) {
            console.error("PDF Export Fault:", err);
            alert("Neural Uplink Protocol Failed: PDF generation interrupted.");
        } finally {
            element.style.cssText = originalStyle;
        }
    };

    if (!analysisResult) return null;

    const riskLevel = analysisResult.score > 80 ? 'OPTIMAL' : analysisResult.score > 50 ? 'STABLE' : 'CRITICAL';
    const riskColor = riskLevel === 'OPTIMAL' ? '#22c55e' : riskLevel === 'STABLE' ? '#eab308' : '#ef4444';

    return (
        <div style={{ marginTop: '2rem' }}>
            <button
                onClick={downloadPDF}
                className="btn-ai"
                style={{
                    background: 'linear-gradient(135deg, var(--primary-color), var(--secondary-color))',
                    color: '#000',
                    fontWeight: 800,
                    padding: '1.2rem 2.5rem',
                    borderRadius: '1.5rem',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '1rem',
                    boxShadow: '0 20px 40px rgba(56, 189, 248, 0.25)',
                    transition: 'all 0.3s ease',
                    border: 'none',
                    cursor: 'pointer'
                }}
            >
                <Download size={24} /> {t.btn}
            </button>

            {/* Hidden Report Template for Capture */}
            <div style={{ position: 'fixed', left: '-10000px', top: '0', zIndex: -1 }}>
                <div ref={reportRef} data-report-container style={{
                    width: '1000px',
                    padding: '80px',
                    background: '#0a0a0c',
                    color: '#ffffff',
                    fontFamily: "'Plus Jakarta Sans', sans-serif"
                }}>
                    {/* Header */}
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '80px', borderBottom: '2px solid rgba(56, 189, 248, 0.2)', paddingBottom: '40px' }}>
                        <div>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '20px' }}>
                                <div style={{ width: '60px', height: '60px', background: 'var(--primary-color)', borderRadius: '15px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                                    <Zap size={35} color="#000" fill="#000" />
                                </div>
                                <h1 style={{ fontSize: '3rem', fontWeight: 800, margin: 0, letterSpacing: '-1px' }}>FinAura <span style={{ color: 'var(--primary-color)' }}>Ultra</span></h1>
                            </div>
                            <p style={{ fontSize: '1rem', color: 'rgba(255,255,255,0.4)', marginTop: '15px', letterSpacing: '4px', fontWeight: 800 }}>{t.title}</p>
                        </div>
                        <div style={{ textAlign: 'right' }}>
                            <p style={{ fontSize: '0.9rem', color: 'rgba(255,255,255,0.5)', letterSpacing: '1px' }}>REPORT KEY: #FA-{Math.floor(Math.random() * 10000000)}</p>
                            <p style={{ fontSize: '1.2rem', fontWeight: 800, marginTop: '10px', color: 'var(--primary-color)' }}>{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
                        </div>
                    </div>

                    {/* Meta Insight Cards */}
                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '30px', marginBottom: '60px' }}>
                        <div style={{ background: 'rgba(56, 189, 248, 0.03)', padding: '30px', borderRadius: '30px', border: '1px solid rgba(56, 189, 248, 0.2)', textAlign: 'center' }}>
                            <p style={{ fontSize: '0.8rem', color: 'rgba(56, 189, 248, 0.7)', fontWeight: 800, marginBottom: '10px', textTransform: 'uppercase' }}>{t.score}</p>
                            <h2 style={{ fontSize: '4.5rem', margin: 0, color: 'var(--primary-color)', fontWeight: 900 }}>{analysisResult.score}</h2>
                        </div>
                        <div style={{ background: 'rgba(255, 255, 255, 0.02)', padding: '30px', borderRadius: '30px', border: '1px solid rgba(255,255,255,0.05)', textAlign: 'center' }}>
                            <p style={{ fontSize: '0.8rem', color: 'rgba(255, 255, 255, 0.4)', fontWeight: 800, marginBottom: '10px', textTransform: 'uppercase' }}>{t.risk}</p>
                            <h2 style={{ fontSize: '2.5rem', margin: 0, color: riskColor, fontWeight: 900, marginTop: '15px' }}>{riskLevel}</h2>
                        </div>
                        <div style={{ background: 'rgba(255, 255, 255, 0.02)', padding: '30px', borderRadius: '30px', border: '1px solid rgba(255,255,255,0.05)', textAlign: 'center' }}>
                            <p style={{ fontSize: '0.8rem', color: 'rgba(255, 255, 255, 0.4)', fontWeight: 800, marginBottom: '10px', textTransform: 'uppercase' }}>RECORDS SYNCED</p>
                            <h2 style={{ fontSize: '2.5rem', margin: 0, color: '#fff', fontWeight: 900, marginTop: '15px' }}>{businessData?.length || 0}</h2>
                        </div>
                    </div>

                    {/* Summary Section */}
                    <div style={{ background: 'rgba(255,255,255,0.02)', padding: '40px', borderRadius: '35px', border: '1px solid rgba(255,255,255,0.05)', marginBottom: '60px' }}>
                        <h3 style={{ fontSize: '1.4rem', fontWeight: 800, marginBottom: '25px', display: 'flex', alignItems: 'center', gap: '15px', color: 'var(--primary-color)' }}>
                            <FileText size={24} /> {t.summary}
                        </h3>
                        <p style={{ color: 'rgba(255,255,255,0.8)', fontSize: '1.1rem', lineHeight: 2, textAlign: 'justify' }}>
                            FinAura Forensic Synthesis has processed {businessData?.length || 0} discrete data points.
                            The analysis indicates a {riskLevel.toLowerCase()} operational trajectory with {analysisResult.score > 70 ? 'high efficiency' : 'notable optimization potential'}.
                            Revenue vectors show significant {analysisResult.score > 60 ? 'stability' : 'volatility'} in the current reporting cycle.
                            We have identified {analysisResult.findings.length} critical focus areas and dispatched {analysisResult.recommendations.length} neural directives for immediate strategic implementation.
                        </p>
                    </div>

                    {/* Trend Analytics */}
                    <div style={{ marginBottom: '60px' }}>
                        <h3 style={{ fontSize: '1.4rem', fontWeight: 800, marginBottom: '30px', display: 'flex', alignItems: 'center', gap: '15px' }}>
                            <TrendingUp size={24} color="var(--primary-color)" /> {t.trends} - <span style={{ color: 'rgba(255,255,255,0.4)', fontSize: '1rem' }}>{yKey} Analysis</span>
                        </h3>
                        <div style={{ height: '350px', background: 'rgba(255,255,255,0.01)', borderRadius: '40px', padding: '40px', border: '1px solid rgba(255,255,255,0.03)' }}>
                            <ResponsiveContainer width="100%" height="100%">
                                <AreaChart data={businessData || []}>
                                    <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" vertical={false} />
                                    <XAxis dataKey={xKey} stroke="rgba(255,255,255,0.3)" fontSize={12} tickLine={false} axisLine={false} />
                                    <YAxis stroke="rgba(255,255,255,0.3)" fontSize={12} tickLine={false} axisLine={false} />
                                    <Tooltip
                                        contentStyle={{ background: '#0a0a0c', border: '1px solid var(--primary-color)', borderRadius: '12px' }}
                                        itemStyle={{ color: '#fff' }}
                                    />
                                    <Area
                                        type="monotone"
                                        dataKey={yKey}
                                        stroke="#38bdf8"
                                        fill="rgba(56, 189, 248, 0.2)"
                                        strokeWidth={4}
                                        isAnimationActive={false}
                                        name={yKey.toUpperCase()}
                                    />
                                    {y2Key && (
                                        <Area
                                            type="monotone"
                                            dataKey={y2Key}
                                            stroke="#818cf8"
                                            fill="rgba(129, 140, 248, 0.1)"
                                            strokeWidth={2}
                                            isAnimationActive={false}
                                            name={y2Key.toUpperCase()}
                                            strokeDasharray="5 5"
                                        />
                                    )}
                                </AreaChart>
                            </ResponsiveContainer>
                        </div>
                        <div style={{ marginTop: '20px', display: 'flex', gap: '30px', padding: '0 20px' }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                                <div style={{ width: '12px', height: '12px', background: '#38bdf8', borderRadius: '3px' }}></div>
                                <span style={{ fontSize: '0.8rem', color: 'rgba(255,255,255,0.5)', fontWeight: 700 }}>{yKey.toUpperCase()}</span>
                            </div>
                            {y2Key && (
                                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                                    <div style={{ width: '12px', height: '12px', background: '#818cf8', borderRadius: '3px' }}></div>
                                    <span style={{ fontSize: '0.8rem', color: 'rgba(255,255,255,0.5)', fontWeight: 700 }}>{y2Key.toUpperCase()}</span>
                                </div>
                            )}
                        </div>
                    </div>

                    {/* Page Break Spacer for Second Page Sections */}
                    <div style={{ height: '350px' }}></div>

                    {/* Strategic Directives Grid */}
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '40px', marginBottom: '60px' }}>
                        <div>
                            <h3 style={{ fontSize: '1.3rem', fontWeight: 800, marginBottom: '25px', display: 'flex', alignItems: 'center', gap: '15px', color: '#ef4444' }}>
                                <AlertCircle size={22} /> {t.focus}
                            </h3>
                            <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                                {analysisResult.findings.map((f, i) => (
                                    <div key={i} style={{ padding: '20px', background: 'rgba(239, 68, 68, 0.05)', borderRadius: '20px', borderLeft: '5px solid #ef4444', fontSize: '0.95rem', color: 'rgba(255,255,255,0.9)' }}>
                                        {f}
                                    </div>
                                ))}
                            </div>
                        </div>
                        <div>
                            <h3 style={{ fontSize: '1.3rem', fontWeight: 800, marginBottom: '25px', display: 'flex', alignItems: 'center', gap: '15px', color: '#22c55e' }}>
                                <Target size={22} /> {t.recommendations}
                            </h3>
                            <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                                {analysisResult.recommendations.map((r, i) => (
                                    <div key={i} style={{ padding: '20px', background: 'rgba(34, 197, 94, 0.05)', borderRadius: '20px', borderLeft: '5px solid #22c55e', fontSize: '0.95rem', color: 'rgba(255,255,255,0.9)' }}>
                                        <strong style={{ color: '#22c55e', display: 'block', marginBottom: '5px' }}>{r.title}</strong>
                                        {r.description}
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>

                    {/* Detailed Data Matrix */}
                    <div style={{ marginTop: '40px' }}>
                        <h3 style={{ fontSize: '1.4rem', fontWeight: 800, marginBottom: '30px', display: 'flex', alignItems: 'center', gap: '15px', color: 'var(--primary-color)' }}>
                            <List size={24} /> {t.details}
                        </h3>
                        <div style={{ background: 'rgba(255,255,255,0.01)', borderRadius: '30px', overflow: 'hidden', border: '1px solid rgba(255,255,255,0.05)' }}>
                            <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
                                <thead>
                                    <tr style={{ background: 'rgba(255,255,255,0.03)' }}>
                                        {Object.keys(businessData?.[0] || {}).slice(0, 5).map((k, i) => (
                                            <th key={i} style={{ padding: '20px', fontSize: '0.8rem', fontWeight: 800, color: 'var(--primary-color)', textTransform: 'uppercase', letterSpacing: '1px' }}>{k}</th>
                                        ))}
                                    </tr>
                                </thead>
                                <tbody>
                                    {(businessData?.slice(0, 10) || []).map((row, i) => (
                                        <tr key={i} style={{ borderBottom: '1px solid rgba(255,255,255,0.02)' }}>
                                            {Object.values(row).slice(0, 5).map((v, j) => (
                                                <td key={j} style={{ padding: '15px 20px', fontSize: '0.9rem', color: 'rgba(255,255,255,0.7)' }}>{String(v)}</td>
                                            ))}
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                            {businessData?.length > 10 && (
                                <p style={{ padding: '20px', fontSize: '0.8rem', color: 'rgba(255,255,255,0.3)', textAlign: 'center' }}>
                                    ... and {businessData.length - 10} more records synthesized.
                                </p>
                            )}
                        </div>
                    </div>

                    {/* Footer */}
                    <div style={{ marginTop: '100px', textAlign: 'center', borderTop: '2px solid rgba(255,255,255,0.05)', paddingTop: '40px' }}>
                        <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '10px', marginBottom: '15px' }}>
                            <Zap size={20} color="var(--primary-color)" />
                            <span style={{ fontWeight: 800, fontSize: '1.2rem' }}>FinAura Ultra</span>
                        </div>
                        <p style={{ fontSize: '0.8rem', color: 'rgba(255,255,255,0.3)', letterSpacing: '5px', textTransform: 'uppercase' }}>{t.generated}</p>
                        <p style={{ fontSize: '0.7rem', color: 'rgba(255,255,255,0.2)', marginTop: '10px' }}>The data contained herein is strictly confidential and intended for strategic auditing purposes only.</p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ForensicReport;

